BRIGHTNESS_THRESHOLD_LOW = 110
BRIGHTNESS_THRESHOLD_HIGH = 255
BLUR_THRESHOLD_LOW = 5
BLUR_THRESHOLD_HIGH = 100
PIXELATION_THRESHOLD_LOW = 0.50
PIXELATION_THRESHOLD_HIGH = 20
WASHED_OUT_PEAK_THRESHOLD = 0.8
WASHED_OUT_LOW_THRESHOLD = 0.1
EYE_DISTANCE_RATIO = 6
MOUTH_OPEN_LOW = 12
MOUTH_OPEN_HIGH = 25
# pitch is not calculated in angles, it is calculated in ratios 
# of distance of two eyes from middele of the nose
PITCH_MIN = 0.9
PITCH_MAX = 1.2
ROLL_ANGLE = 10
BACKGROUND_COLOR_THRESHOLD_LOW= 100
BACKGROUND_COLOR_THRESHOLD_HIGH= 255
